<a href="https://colab.research.google.com/github/mtxslv/EveryoneNeedsAHobbie/blob/master/simplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For optimization problems, we need to delimitate a method, called simplex. I will write it down here, but it will be writed again in MatLab, Scilab, etc.

Our goal is to maximize (or minimize) a function z given by 
> $z = \sum_{j = 1}^{n}c_jx_j$

This function is called **objective function** and is limited by the following inequations:
> $\sum_{j = 1}^{n}a_{ij}x_j \leq b_i ,(i=1,...,m) \land x_j \geq 0, (j=1...n)$

First of all, we need to add one slack variable inside each inequality. It will change the system of inequations, leading to the next system:

>$\sum_{j = 1}^{n}a_{ij}x_j + x_{n+i} = b_i ,(i=1,...,m) \land x_{n+i} \geq 0, (j=1...n)$

After that, we put the right member of z to the left side and get:
> $z - \sum_{j = 1}^{n}c_jx_j = 0$

If we suppose there are $0z's$ in each of the constraints equations and $0x_{n+i}$, we can get the system:
> $z - \sum_{j = 1}^{n}c_jx_j + 0x_{n+i}= 0 \\
0z + \sum_{j = 1}^{n}a_{ij}x_j + x_{n+i} = b_i $

This last system can go into a matrix, and from there we delimitate our algorithm.


In this first moment, we will consider our algorithm **just solves maximization problems**.

In [0]:
#important importation
import numpy as np

In [0]:
def simplex(tabela, num_var_basic):
  """
  input
    tabela: a matriz aumentada, na forma canônica, que contém a coluna da variável independente z.
            A última coluna é considerada a dos termos idependentes
    num_var_basic: a quantidade de variáveis básicas na matriz canônica aumentada.
  output
    o valor ótimo de z.
  """
  import numpy as np
  # vamos definir algumas variáveis
  
  # matriz a ser iterada
  matriz = tabela[:,1:]
  print(matriz)
  
  # vetor dos termos limitantes
  q = matriz[:,-1]
  print(q)
  
  #vetor que contém as colunas das variáveis básicas:
  # Tenha cuidado! estamos lidando com a matriz, não com a tabela. 
  # Logo, estamos com uma coluna a menos. Além disso, as colunas começam
  # com 0
  base = np.array(np.arange(num_var_basic,matriz.shape[1]-1)) 
  print(base)
  
  # Enquanto ouver valores negativos na primeira linha da matriz, 
  # o algoritmo ainda não achou o ótimo da função
  while(np.amin(matriz[0,:])<0):
    #print("heythere")
    # Primeiro passo é achar a variável não básica que deve entrar na base
    pra_entrar = matriz[0,:].argmin() 
    # Depois é achar quem sai
    l = (matriz[:,-1]/matriz[:,pra_entrar]).argmin() # l é a linha da variável que vai sair
    
    # tornar o pivô igual a 1
    matriz[l,:] = matriz[l,:]/matriz[l,pra_entrar]    
  
    #agora é só zerar a coluna
    for p in range(matriz.shape[0]):
      if (p!=l):
        print("cheguei qui")
        matriz[p,:] = matriz[p,:] - matriz[p,:]*(matriz[p,pra_entrar]/matriz[l,pra_entrar])
  print(matriz)
  return matriz[0,-1]      
        

In [35]:
tabela_teste = np.array([[1, -12, -15, 0, 0, 0, 0, 0],
                [0, 1, 0, 1, 0, 0, 0, 3],
                [0, 0, 1, 0, 1, 0, 0, 4],
                [0, 1, 1, 0, 0, 1, 0,6],
                [0, 1, 3, 0, 0, 0, 1, 13]])
n_var_basic_test = 2

a =simplex(tabela_teste, n_var_basic_test)

[[-12 -15   0   0   0   0   0]
 [  1   0   1   0   0   0   3]
 [  0   1   0   1   0   0   4]
 [  1   1   0   0   1   0   6]
 [  1   3   0   0   0   1  13]]
[ 0  3  4  6 13]
[2 3 4 5]
cheguei qui
cheguei qui
cheguei qui
cheguei qui
[[  0   1   0   0   0   0   0]
 [  1   0   1   0   0   0   3]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [ -2  -6   0   0   0  -2 -26]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: divide by zero encountered in true_divide


In [31]:
a

0

In [21]:
(tabela_teste[1:,-1] / tabela_teste[1:,2])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 4.        , 6.        , 4.33333333])

In [22]:
(tabela_teste[1:,-1] / tabela_teste[1:,2]).argmin()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


1